'use strict';
const $=id=>document.getElementById(id), norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let places=[],filtered=[],limit=24,timer;
const matchesSection=(p,s)=>!s||p.sections.some(x=>(x.match(/\d+/g)||[]).some(n=>Number(n)===Number(s)));
function filter(){const q=norm($('query').value).trim().split(/\s+/).filter(Boolean),s=$('section').value.trim();filtered=places.filter(p=>(!$('city').value||p.city===$('city').value)&&(!$('zone').value||p.zone===Number($('zone').value))&&matchesSection(p,s)&&(!$('mrj').checked||p.notes.some(n=>n.includes('MRJ')))&&q.every(t=>norm(p.name+' '+p.address+' '+p.city).includes(t)));limit=24;render();}
function render(){const s=$('section').value.trim();$('count').textContent=`${filtered.length} ${filtered.length===1?'local encontrado':'locais encontrados'} · ${places.length} na base`;let shown=filtered.slice(0,limit);$('cards').innerHTML=shown.length?shown.map(p=>{const ix=places.indexOf(p),map='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.address+', '+p.city+', Acre, Brasil');return `<article class="card"><p class="meta">${esc(p.city)} <span aria-hidden="true">·</span> ${p.zone}ª zona eleitoral</p><h3>${esc(p.name)}</h3><p class="address">⌖ ${esc(p.address)}</p><span class="section-label">SEÇÕES ELEITORAIS</span><div class="chips">${p.sections.map(n=>`<span class="chip ${s&&(n.match(/\d+/g)||[]).some(v=>Number(v)===Number(s))?'hit':''}">${esc(n)}</span>`).join('')}</div>${p.notes.length?`<div class="notes">${p.notes.map(n=>`<span class="note">${esc(n)}</span>`).join('')}</div>`:''}${p.details.length?`<p class="details">${p.details.map(esc).join(' · ')}</p>`:''}<div class="actions"><a href="${esc(map)}" target="_blank" rel="noopener">Ver no mapa ↗</a><button data-copy="${ix}" aria-label="Copiar endereço de ${esc(p.name)}">Copiar endereço</button></div></article>`;}).join(''):'<div class="empty"><h3>Nenhum local encontrado</h3><p>Confira a zona e a seção ou tente apenas uma parte do nome.</p><button id="empty-clear">Limpar filtros</button></div>';$('more').hidden=limit>=filtered.length;$('empty-clear')?.addEventListener('click',clear);}
function clear(){['query','city','zone','section'].forEach(id=>$(id).value='');$('mrj').checked=false;filter();}
function toast(message){clearTimeout(timer);$('toast').textContent=message;$('toast').hidden=false;timer=setTimeout(()=>$('toast').hidden=true,3500);}
$('cards').addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(!b)return;const p=places[Number(b.dataset.copy)];try{await navigator.clipboard.writeText(`${p.name}\n${p.address}\n${p.city} - AC\nZona ${p.zone} · Seções: ${p.sections.join(', ')}\nFonte: TRE-AC · Consulta em 03/10/2026`);toast('Endereço copiado!');}catch{toast('Não foi possível copiar. Selecione o endereço no cartão.');}});
['query','city','zone','section','mrj'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='section')$('section').value=$('section').value.replace(/\D/g,'');filter();}));
$('clear').addEventListener('click',clear);$('more').addEventListener('click',()=>{limit+=24;render();});$('print').addEventListener('click',()=>{limit=filtered.length;render();window.print();});
fetch('./data.json').then(r=>{if(!r.ok)throw Error('load');return r.json();}).then(d=>{places=d.places;for(const c of [...new Set(places.map(p=>p.city))].sort((a,b)=>a.localeCompare(b,'pt-BR'))){const o=new Option(c,c);$('city').add(o);}for(const z of [...new Set(places.map(p=>p.zone))].sort((a,b)=>a-b))$('zone').add(new Option(`${z}ª zona eleitoral`,z));$('total').textContent=places.length;filter();}).catch(()=>{$('count').textContent='Não foi possível carregar os locais.';$('cards').innerHTML='<div class="empty"><h3>A consulta está indisponível</h3><p>Recarregue a página ou consulte diretamente o TRE-AC pelo link no topo.</p></div>';toast('Falha ao carregar os dados.');});
