'use strict';
const $=id=>document.getElementById(id),norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let places=[],filtered=[],scope=[],limit=24,activeSection='',mode='search',timer,loaded=false;
const matchesSection=(p,s)=>!s||p.sections.some(n=>(n.match(/\d+/g)||[]).some(v=>Number(v)===Number(s)));
function destination(p){const lat=Number(p.latitude),lon=Number(p.longitude);if(p.latitude!=null&&p.longitude!=null&&String(p.latitude).trim()!==''&&String(p.longitude).trim()!==''&&Number.isFinite(lat)&&Number.isFinite(lon)&&Math.abs(lat)<=90&&Math.abs(lon)<=180)return `${lat},${lon}`;return [p.name,p.address,p.city,'Acre','Brasil'].filter(Boolean).join(', ');}
function mapLinks(p,origin){const query=destination(p),map=new URL('https://www.google.com/maps/search/'),route=new URL('https://www.google.com/maps/dir/');map.searchParams.set('api','1');map.searchParams.set('query',query);route.searchParams.set('api','1');route.searchParams.set('destination',query);route.searchParams.set('dir_action','navigate');if(origin)route.searchParams.set('origin',origin);if(p.placeId){map.searchParams.set('query_place_id',p.placeId);route.searchParams.set('destination_place_id',p.placeId);}return {map:map.href,route:route.href};}
function toast(m){clearTimeout(timer);$('toast').textContent=m;$('toast').hidden=false;timer=setTimeout(()=>$('toast').hidden=true,4500);}
function back(){ $('results').hidden=true;$('home').hidden=false;$('section').value='';$('browse-query').value='';window.scrollTo({top:0,behavior:'smooth'});$('section').focus({preventScroll:true});}
function show(){ $('home').hidden=true;$('results').hidden=false;$('browse').hidden=mode!=='list';$('mode-label').textContent=mode==='list'?'TODOS OS LOCAIS':'RESULTADO';$('result-title').textContent=mode==='list'?'Locais de votação':filtered.length===1?'Seu local de votação':'Resultado da pesquisa';$('multiple').hidden=mode!=='search'||filtered.length<=1||Boolean($('zone').value);limit=24;render();window.scrollTo({top:0,behavior:'smooth'});$('results').focus({preventScroll:true});}
function baseFilter(p){return (!$('city').value||p.city===$('city').value)&&(!$('zone').value||p.zone===Number($('zone').value));}
function search(){if(!loaded)return;const s=$('section').value.trim();if(!/^\d+$/.test(s)||Number(s)<=0){toast('Informe uma seção válida, conforme seu título ou e-Título.');$('section').focus();return;}mode='search';activeSection=s;filtered=places.filter(p=>baseFilter(p)&&matchesSection(p,s));show();}
function listAll(){if(!loaded)return;mode='list';activeSection='';scope=places.filter(baseFilter);filtered=[...scope];$('browse-query').value='';show();}
function render(){ $('count').textContent=`${filtered.length} ${filtered.length===1?'local encontrado':'locais encontrados'}${mode==='search'?' para a seção '+activeSection:''}`;$('cards').innerHTML=filtered.length?filtered.slice(0,limit).map(p=>{const id=places.indexOf(p),links=mapLinks(p);return `<article class="card"><p class="meta">${esc(p.city)} · ${p.zone}ª zona eleitoral</p><h2>${esc(p.name)}</h2><p class="address">⌖ ${esc(p.address)}</p><span class="section-label">SEÇÕES ATENDIDAS</span><div class="chips">${p.sections.map(n=>`<span class="chip ${activeSection&&matchesSection({sections:[n]},activeSection)?'hit':''}">${esc(n)}</span>`).join('')}</div>${p.notes.length?`<p class="notes">${p.notes.map(esc).join(' · ')}</p>`:''}${p.details.length?`<p class="notes">${p.details.map(esc).join(' · ')}</p>`:''}<div class="actions"><a class="map-button" href="${esc(links.map)}" target="_blank" rel="noopener">⌖ Ver no mapa</a><button class="route-button" data-route="${id}">↗ Traçar rota até o local</button><button class="copy-button" data-copy="${id}">Copiar endereço</button></div></article>`;}).join(''):`<div class="empty"><h2>Nenhum local encontrado</h2><p>${mode==='search'?'Pode haver um erro de digitação. Confira a seção, a zona e o município no título ou no e-Título e tente novamente.':'Tente outro nome ou endereço, ou volte e ajuste o município e a zona.'}</p></div>`;$('more').hidden=limit>=filtered.length;}
$('search-form').addEventListener('submit',e=>{e.preventDefault();search();});$('section').addEventListener('input',()=>{$('section').value=$('section').value.replace(/\D/g,'');});$('list-all').addEventListener('click',listAll);$('back').addEventListener('click',back);$('new-search').addEventListener('click',back);$('more').addEventListener('click',()=>{limit+=24;render();});$('browse-query').addEventListener('input',()=>{const terms=norm($('browse-query').value).trim().split(/\s+/).filter(Boolean);filtered=scope.filter(p=>terms.every(t=>norm(p.name+' '+p.address+' '+p.city).includes(t)));limit=24;render();});
$('cards').addEventListener('click',async e=>{const copy=e.target.closest('[data-copy]'),route=e.target.closest('[data-route]');if(copy){const p=places[Number(copy.dataset.copy)];try{await navigator.clipboard.writeText(`${p.name}\n${p.address}\n${p.city} - AC\nZona ${p.zone} · Seções: ${p.sections.join(', ')}\nFonte: TRE-AC · Consulta em 03/10/2026`);toast('Endereço copiado!');}catch{toast('Não foi possível copiar. Selecione o endereço no cartão.');}}if(route){const p=places[Number(route.dataset.route)];const tab=window.open('about:blank','_blank');if(!tab){toast('Permita abrir uma nova aba para traçar a rota.');return;}tab.opener=null;tab.document.title='Preparando rota';tab.document.body.textContent='Preparando sua rota. Se solicitado, permita acesso à localização.';route.disabled=true;const open=origin=>{if(!tab.closed)tab.location.replace(mapLinks(p,origin).route);route.disabled=false;};if(!navigator.geolocation){open();return;}navigator.geolocation.getCurrentPosition(pos=>open(`${pos.coords.latitude},${pos.coords.longitude}`),()=>{toast('Localização indisponível. Informe o ponto de partida no Google Maps.');open();},{enableHighAccuracy:false,timeout:10000,maximumAge:60000});}});
fetch('./data.json').then(r=>{if(!r.ok)throw Error('load');return r.json();}).then(d=>{places=d.places;for(const city of [...new Set(places.map(p=>p.city))].sort((a,b)=>a.localeCompare(b,'pt-BR')))$('city').add(new Option(city,city));for(const z of [...new Set(places.map(p=>p.zone))].sort((a,b)=>a-b))$('zone').add(new Option(`${z}ª zona eleitoral`,z));$('total').textContent=places.length;loaded=true;$('search').disabled=false;$('list-all').disabled=false;}).catch(()=>{toast('Não foi possível carregar os locais. Recarregue a página ou consulte o TRE-AC.');$('search').textContent='Dados indisponíveis';});
